# Generated by Django 2.1.7 on 2019-02-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('color', models.TextField(blank=True, null=True)),
                ('director_name', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('actor_2_name', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('actor_1_name', models.TextField(blank=True, null=True)),
                ('movie_title', models.TextField(blank=True, null=True)),
                ('actor_3_name', models.TextField(blank=True, null=True)),
                ('plot_keywords', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('title_year', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
